### ISSUE TITLE
如何将CLI部署至linux-arm

### ISSUE THREAD

**Issue by H15teve** [Berrysoft/TsinghuaNetUWP#12]
尝试下载源码并发布至linux-arm(Raspberry Pi 4B)，但先后遭遇不支持cross-compilation等错误。对.NET开发不是很了解，还请作者解惑。

**Comment by Berrysoft** [comment]
诶我刚看见这个issue……解决了吗？.NET Core应该可以在linux arm平台运行的，不至于交叉编译
