### ISSUE TITLE
UWP安装时提示需要安装证书

### ISSUE THREAD

**Issue by Kevin99z** [Berrysoft/TsinghuaNetUWP#3]
UWP安装时提示需要安装证书，版本3.2.68。我自己的虚拟机安装时卡在16%

**Comment by Kevin99z** [comment]
（安装了自带的证书，不知道为什么没用）

**Comment by Berrysoft** [comment]
@Kevin99z 右键`Add-AppDevPackage.ps1`用PowerShell运行试试？（另：3.2.69已经发布了）
