### ISSUE TITLE
Ubuntu 18.04 LTS中因glibc版本不符而无法运行

### ISSUE THREAD

**Issue by Minys233** [Berrysoft/TsinghuaNetUWP#7]
从Releases页下载的最新版的`TsinghuaNet.CLI.AnyCPU.zip`，解压后运行会有如下现象：
``` bash
➜  ~ ./TsinghuaNet.CLI                
./TsinghuaNet.CLI: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./TsinghuaNet.CLI)
➜  ~ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
然而不幸的是，glibc并不是想安装就能安装的，除非更新系统，而我又恰好没有接触过C#，不能自己编译。能否在交叉编译的时候增加一些支持的glibc版本，谢谢！

**Comment by Berrysoft** [comment]
@Minys233 `AnyCPU`版本是依赖.NET Core 3.0的，而且没有可执行的`TsinghuaNet.CLI`文件。如果是`Linux64`版本，这个是AOT版本，而且目前工具链还不支持交叉编译（我在自己的电脑上编译的）。建议下载.NET Core 3.0 Runtime，如果想要AOT版本就安装.NET Core 3.0 SDK，然后自己编译。
我会考虑把编译过程放到CI上，看看能不能得到合适的版本。

**Comment by Berrysoft** [comment]
@Minys233 已经发布了新版本，Linux版本使用的是Azure上的Ubuntu 16.04编译的，你试一下？
