### ISSUE TITLE
客户端失效了。。。

### ISSUE THREAD

**Issue by cescchen1990** [Berrysoft/TsinghuaNetUWP#9]
好像信息办升级了界面，没法登录了。。。

**Comment by cescchen1990** [comment]
大哥们有办法解决一下么。。。

**Comment by Berrysoft** [comment]
不好意思我不在学校，等回去再解决吧。

**Comment by Berrysoft** [comment]
@cescchen1990 能说一下是哪个界面升级了吗？我挂vpn回去看没发现升级的

**Comment by cescchen1990** [comment]
现在的主要问题是用你那个客户端登不上去。。。网页登录没问题。。

**Comment by Berrysoft** [comment]
请问是无线网还是有线网？无线网的话名称（SSID）是什么？登录页面的网址是多少？客户端无法登录的话有没有错误提示？从网页登录后，用客户端能否查看在线状态？

**Comment by cescchen1990** [comment]
有线。http://auth4.tsinghua.edu.cn/index_159.html跳转
https://auth4.tsinghua.edu.cn/srun_portal_pc.php?ac_id=159&
；有错误提示，就是显示error；网页登陆后，客户端可以看在线状态。

**Comment by Berrysoft** [comment]
@cescchen1990 谢谢！暂时修复了，一会在release中发布。

**Comment by Berrysoft** [comment]
@cescchen1990 发布了新的release，如果有问题reopen。

**Comment by Minys233** [comment]
确实，自己写的脚本运行大半年了月初离奇失效，看到这个讨论明白了，看了网页代码，似乎现在要强制跳转。懒得写了，直接做一次拿来党，感谢！

**Comment by Berrysoft** [comment]
不用谢。现在官方文档建议的方法是访问
* http://3.3.3.3/
* http://9.9.9.9/
* http://[333::3]/
* http://[999::9]/

做跳转，我现在就是用这个。不过等到登录成功，这几个地址又没有办法跳转了，所以还需要缓存一下ac_id。
